#include "stm32f4xx_hal.h"
#include <math.h>
#include <stdbool.h>

#define WHEEL_BASE_M      0.18f
#define MAX_SPEED_MPS     0.35f
#define LINEAR_GAIN       0.6f
#define ANGULAR_GAIN      2.0f
#define POSITION_EPS_M    0.05f
#define HEADING_EPS_RAD   0.05f

// Simple pose structure for planar motion
typedef struct
{
    float x;
    float y;
    float yaw;
} Pose2D;

// Waypoint definition: go to (x, y) in meters and desired yaw
typedef struct
{
    float x;
    float y;
    float yaw;
} Waypoint;

static Pose2D current_pose = {0.0f, 0.0f, 0.0f};
static const Waypoint path[] = {
    {0.0f, 0.0f, 0.0f},
    {0.5f, 0.0f, 0.0f},
    {0.5f, 0.5f, (float)M_PI_2},
    {0.0f, 0.5f, (float)M_PI},
    {0.0f, 0.0f, (float)-M_PI_2},
};
static const uint8_t path_length = sizeof(path) / sizeof(path[0]);
static uint8_t target_index = 0;

// Forward declarations
static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_TIM3_Init(void);
static void update_odometry(void);
static void set_differential_velocity(float linear, float angular);

// Hardware handles
TIM_HandleTypeDef htim3;

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_TIM3_Init();

    // Enable motor PWM outputs
    HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_1);
    HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_2);

    while (1)
    {
        update_odometry();

        const Waypoint *target = &path[target_index];
        float dx = target->x - current_pose.x;
        float dy = target->y - current_pose.y;
        float distance = sqrtf(dx * dx + dy * dy);

        // Desired heading toward the waypoint
        float desired_heading = atan2f(dy, dx);
        float heading_error = desired_heading - current_pose.yaw;

        // Wrap heading to [-pi, pi]
        while (heading_error > (float)M_PI)
            heading_error -= 2.0f * (float)M_PI;
        while (heading_error < -(float)M_PI)
            heading_error += 2.0f * (float)M_PI;

        float linear_cmd = LINEAR_GAIN * distance;
        if (linear_cmd > MAX_SPEED_MPS)
            linear_cmd = MAX_SPEED_MPS;

        // When close, align with the waypoint yaw instead of pointing at the target
        float angular_target = (distance < POSITION_EPS_M) ? (target->yaw - current_pose.yaw) : heading_error;
        float angular_cmd = ANGULAR_GAIN * angular_target;

        set_differential_velocity(linear_cmd, angular_cmd);

        // Move to next waypoint when close enough and aligned
        if ((distance < POSITION_EPS_M) && (fabsf(angular_target) < HEADING_EPS_RAD))
        {
            if (target_index < path_length - 1)
            {
                target_index++;
            }
            else
            {
                // Stop at the end of the path
                set_differential_velocity(0.0f, 0.0f);
            }
        }

        HAL_Delay(10);
    }
}

static void update_odometry(void)
{
    // TODO: Replace with encoder + IMU integration.
    // For now, assume constant velocity and integrate using timer period
    // This placeholder keeps the control logic compilable.
}

static void set_differential_velocity(float linear, float angular)
{
    float v_left = linear - (angular * WHEEL_BASE_M * 0.5f);
    float v_right = linear + (angular * WHEEL_BASE_M * 0.5f);

    // Convert to PWM values for your hardware; clamp to [0, MAX_SPEED_MPS]
    if (v_left > MAX_SPEED_MPS)
        v_left = MAX_SPEED_MPS;
    if (v_right > MAX_SPEED_MPS)
        v_right = MAX_SPEED_MPS;
    if (v_left < -MAX_SPEED_MPS)
        v_left = -MAX_SPEED_MPS;
    if (v_right < -MAX_SPEED_MPS)
        v_right = -MAX_SPEED_MPS;

    // Map speeds to PWM duty cycles (0-100%)
    uint32_t left_pwm = (uint32_t)((fabsf(v_left) / MAX_SPEED_MPS) * (__HAL_TIM_GET_AUTORELOAD(&htim3)));
    uint32_t right_pwm = (uint32_t)((fabsf(v_right) / MAX_SPEED_MPS) * (__HAL_TIM_GET_AUTORELOAD(&htim3)));

    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_1, left_pwm);
    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_2, right_pwm);

    // TODO: Control motor direction pins based on sign of v_left and v_right
}

static void SystemClock_Config(void)
{
    // Configure system clock to match your board. Generated by STM32CubeMX normally.
}

static void MX_GPIO_Init(void)
{
    // Initialize GPIO pins for motor direction and encoders.
}

static void MX_TIM3_Init(void)
{
    // Configure TIM3 for PWM output on CH1/CH2. Replace with CubeMX output.
}

#ifdef  USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line)
{
    (void)file;
    (void)line;
    while (1)
    {
    }
}
#endif

